// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rufflogix/computer-network-project/internal/controller"
	"github.com/rufflogix/computer-network-project/internal/repository"
	"github.com/rufflogix/computer-network-project/internal/service"
)

// Injectors from wire.go:

func InitializeWSHandler() controller.WSHandler {
	chatRepository := repository.NewChatRepository()
	chatService := service.NewChatService(chatRepository)
	wsHandler := controller.NewWSHandler(chatService)
	return wsHandler
}

func InitializeSSEHandler() controller.SSEHandler {
	sseHandler := controller.NewSSEHandler()
	return sseHandler
}

func InitializeHTTPHandler() controller.HTTPHandler {
	httpHandler := controller.NewHTTPHander()
	return httpHandler
}
