// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rufflogix/computer-network-project/internal/controller"
	"github.com/rufflogix/computer-network-project/internal/repository"
	"github.com/rufflogix/computer-network-project/internal/service"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeHandlers(db *mongo.Database) ServerHandlers {
	chatRepository := repository.NewChatRepository()
	userRepository := repository.NewUserRepository(db)
	chatService := service.NewChatService(chatRepository, userRepository)
	invitationRepository := repository.NewInvitationRepository()
	friendshipRepository := repository.NewFriendshipRepository()
	notificationRepository := repository.NewNotificationRepository()
	roomService := service.NewRoomService()
	notificationService := service.NewNotificationService(notificationRepository, friendshipRepository, chatRepository, userRepository, roomService)
	invitationService := service.NewInvitationService(invitationRepository, chatRepository, friendshipRepository, notificationService, userRepository)
	authService := service.NewAuthService(userRepository)
	httpHandler := controller.NewHTTPHandler(chatService, invitationService, notificationService, authService, roomService)
	wsHandler := controller.NewWSHandler(chatService, roomService, notificationService, invitationService)
	authHandler := controller.NewAuthHandler(authService)
	serverHandlers := provideServerHandlers(httpHandler, wsHandler, authHandler)
	return serverHandlers
}

// wire.go:

type ServerHandlers struct {
	HTTP controller.HTTPHandler
	WS   controller.WSHandler
	Auth controller.AuthHandler
}

func provideServerHandlers(
	httpHandler controller.HTTPHandler,
	wsHandler controller.WSHandler,
	authHandler controller.AuthHandler,
) ServerHandlers {
	return ServerHandlers{
		HTTP: httpHandler,
		WS:   wsHandler,
		Auth: authHandler,
	}
}
